server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    host: 192.168.1.101
    username: leyou
    password: leyou
  redis:
    host: 192.168.25.133
    port: 6379
ly:
  sms:
    accessKeyId:
    accessKeySecret:
    signName: ly商城 #签名
    verifyCodeTemplate: SMS_180058287 #验证码模板
debug: true
