server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB #文件大小限制 限制文件上传大小
      max-request-size: 20MB #一次请求的限制，一次请求可以有多个文件
#EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.25.133:22122
ly:
  upload:
    base_url: http://image.leyou.com/
    allowTypes:
      - image/jpeg
      - image/png
      - image/jpg
      - image/bmp
