server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.25.133
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

ly:
  jwt:
    pubKeyPath: G:\leyou-server-zongjie\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN