spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    virtual-host: /leyou
    host: 192.168.1.101
    username: leyou
    password: leyou
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka